#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

#--------------------------------------------------------------------------------------------
# PARAMETERS RETURNED BY MATLAB CALIBRATION HERE
# They will be used to pre-rectify images before giving them to orbslam
Camera.type: "Rectified"

Camera.width: 1440
Camera.height: 1080

Camera1.fx: 1061.90838
Camera1.fy: 1065.08245
Camera1.cx: 778.19368
Camera1.cy: 553.85699

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.000000000000
Camera1.p2: 0.000000000000

Camera2.fx: 1060.22456
Camera2.fy: 1063.51251
Camera2.cx: 782.09116
Camera2.cy: 582.52751

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.000000000000
Camera2.p2: 0.000000000000

# Not needed for rectified cameras
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, -0.055,
         0.0, 1.0, 0.0, 0,
         0.0, 0.0, 1.0, 0,
         0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]
# END OF MATLAB PARAMETERS
#--------------------------------------------------------------------------------------------

# Distance in meters of the two cameras
Stereo.b: 0.0551

# Camera frames per second
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 10.0

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 4000

#--------------------------------------------------------------------------------------------
# The changing of the following parameters should not infect the resul too much
#--------------------------------------------------------------------------------------------

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 5
ORBextractor.minThFAST: 1

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
